export const OFFER_ADD_SUCCESS='OFFER_ADD_SUCCESS'
export const OFFER_FETCH_SUCCESS='OFFER_FETCH_SUCCESS'
export const OFFER_FETCH_ERROR='OFFER_FETCH_ERROR'
export const OFFER_FETCH_REQUEST='OFFER_FETCH_REQUEST'