export const ADMIN_FETCH_REQUEST='ADMIN_FETCH_REQUEST'
export const ADMIN_FETCH_SUCCESS='ADMIN_FETCH_SUCCESS'
export const ADMIN_FETCH_ERROR='ADMIN_FETCH_ERROR'
export const ADMIN_FETCH_VERIFY='ADMIN_FETCH_VERIFY'