export const ORDER_ADD_SUCCESS='ORDER_ADD_SUCCESS'
export const ORDER_FETCH_SUCCESS='ORDER_FETCH_SUCCESS'
export const ORDER_FETCH_ERROR='ORDER_FETCH_ERROR'
export const ORDER_FETCH_REQUEST='ORDER_FETCH_REQUEST'

export const SALES_REPORT_FETCH_SUCCESS='SALES_REPORT_FETCH_SUCCESS'
export const SALES_REPORT_FETCH_ERROR='SALES_REPORT_FETCH_ERROR'
export const SALES_REPORT_FETCH_REQUEST='SALES_REPORT_FETCH_REQUEST'